spring:
  application:
    name: quiz-aggregator-service  

server:
  port: 8100 

logging:
  level:
    #root: ERROR
    '[org.springframework.web]': ERROR
    '[com.quizforevent.microservices.quizaggregatorservice]': INFO
    
 