apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: quiz-aggregator
  name: quiz-aggregator
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-aggregator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quiz-aggregator
        version: V1.0.2
    spec:
      containers:
      - image: cpruvost/cn-quiz-aggregator-service:1.0.2-SNAPSHOT
        imagePullPolicy: Always
        name: cn-quiz-aggregator-service
        envFrom:
          - configMapRef:
              name: quiz-aggregator
#        env:
#          - name: QUIZ_URI
#            value: http://quiz
       
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quiz-aggregator
  name: quiz-aggregator
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: quiz-aggregator
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  QUIZ_URI: http://quiz
kind: ConfigMap
metadata:
  name: quiz-aggregator
  namespace: default
