apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: quiz-aggregator-application
  namespace: argocd
spec: 
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: src/main/resources/kube 
    repoURL: "https://github.com/cpruvost/quiz-aggregator-service.git"
    targetRevision: main
    directory:
      recurse: false
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    #syncOptions:
      #- CreateNamespace=true